// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Cor1440Gen__AcfechapfController from "./cor1440_gen/acfechapf_controller"
application.register("cor1440-gen--acfechapf", Cor1440Gen__AcfechapfController)

import Cor1440Gen__PfDuracionController from "./cor1440_gen/pf_duracion_controller"
application.register("cor1440-gen--pf-duracion", Cor1440Gen__PfDuracionController)

import Cor1440Gen__PfMontospesosController from "./cor1440_gen/pf_montospesos_controller"
application.register("cor1440-gen--pf-montospesos", Cor1440Gen__PfMontospesosController)

import EnviarautomaticoController from "./enviarautomatico_controller"
application.register("enviarautomatico", EnviarautomaticoController)

import InicializaController from "./inicializa_controller"
application.register("inicializa", InicializaController)

import Msip__BitacoraapController from "./msip/bitacoraap_controller"
application.register("msip--bitacoraap", Msip__BitacoraapController)

import Msip__CancelarVacioEsEliminarController from "./msip/cancelar_vacio_es_eliminar_controller"
application.register("msip--cancelar-vacio-es-eliminar", Msip__CancelarVacioEsEliminarController)

import Msip__EnviarautomaticoController from "./msip/enviarautomatico_controller"
application.register("msip--enviarautomatico", Msip__EnviarautomaticoController)

import Msip__FiltroTanController from "./msip/filtro_tan_controller"
application.register("msip--filtro-tan", Msip__FiltroTanController)

import Msip__GeodepController from "./msip/geodep_controller"
application.register("msip--geodep", Msip__GeodepController)

import Msip__SindocautController from "./msip/sindocaut_controller"
application.register("msip--sindocaut", Msip__SindocautController)

import PersonaPptController from "./persona_ppt_controller"
application.register("persona-ppt", PersonaPptController)

import RapidobenefcasoController from "./rapidobenefcaso_controller"
application.register("rapidobenefcaso", RapidobenefcasoController)

import Res1612Controller from "./res1612_controller"
application.register("res1612", Res1612Controller)

import RespuestacasoController from "./respuestacaso_controller"
application.register("respuestacaso", RespuestacasoController)

import Sivel2Gen__ContarAutomaticoController from "./sivel2_gen/contar_automatico_controller"
application.register("sivel2-gen--contar-automatico", Sivel2Gen__ContarAutomaticoController)

import Sivel2Gen__EdadController from "./sivel2_gen/edad_controller"
application.register("sivel2-gen--edad", Sivel2Gen__EdadController)

import Sivel2Gen__EnviarFichaCasoController from "./sivel2_gen/enviar_ficha_caso_controller"
application.register("sivel2-gen--enviar-ficha-caso", Sivel2Gen__EnviarFichaCasoController)

import Sivel2Gen__FiltroAvanzadoController from "./sivel2_gen/filtro_avanzado_controller"
application.register("sivel2-gen--filtro-avanzado", Sivel2Gen__FiltroAvanzadoController)

import Sivel2Gen__MapaosmController from "./sivel2_gen/mapaosm_controller"
application.register("sivel2-gen--mapaosm", Sivel2Gen__MapaosmController)

import Sivel2Gen__PlotlyActosController from "./sivel2_gen/plotly_actos_controller"
application.register("sivel2-gen--plotly-actos", Sivel2Gen__PlotlyActosController)

import VisibuemController from "./visibuem_controller"
application.register("visibuem", VisibuemController)
