// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InicializaController from "./inicializa_controller"
application.register("inicializa", InicializaController)

import Msip__BitacoraapController from "./msip/bitacoraap_controller"
application.register("msip--bitacoraap", Msip__BitacoraapController)

import Msip__CancelarVacioEsEliminarController from "./msip/cancelar_vacio_es_eliminar_controller"
application.register("msip--cancelar-vacio-es-eliminar", Msip__CancelarVacioEsEliminarController)

import Msip__FiltroTanController from "./msip/filtro_tan_controller"
application.register("msip--filtro-tan", Msip__FiltroTanController)

import Msip__GeodepController from "./msip/geodep_controller"
application.register("msip--geodep", Msip__GeodepController)

import Msip__SindocautController from "./msip/sindocaut_controller"
application.register("msip--sindocaut", Msip__SindocautController)

import PersonaPptController from "./persona_ppt_controller"
application.register("persona-ppt", PersonaPptController)

import RapidobenefcasoController from "./rapidobenefcaso_controller"
application.register("rapidobenefcaso", RapidobenefcasoController)

import Res1612Controller from "./res1612_controller"
application.register("res1612", Res1612Controller)

import RespuestacasoController from "./respuestacaso_controller"
application.register("respuestacaso", RespuestacasoController)

import Sivel2Gen__EdadController from "./sivel2_gen/edad_controller"
application.register("sivel2-gen--edad", Sivel2Gen__EdadController)

import Sivel2Gen__EnviarFichaCasoController from "./sivel2_gen/enviar_ficha_caso_controller"
application.register("sivel2-gen--enviar-ficha-caso", Sivel2Gen__EnviarFichaCasoController)

import Sivel2Gen__MotorController from "./sivel2_gen/motor_controller"
application.register("sivel2-gen--motor", Sivel2Gen__MotorController)

import VisibuemController from "./visibuem_controller"
application.register("visibuem", VisibuemController)
