image: alpine:latest

variables:
  POSTGRES_ENABLED: "true"
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: sijrscol_pru
  POSTGRES_HOST_AUTH_METHOD: trust
  RAILS_ENV: test
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "true"


stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update -yy && apt-get install build-essential libpq-dev -y
    - bundle install
    - bundle exec rails db:setup
    - yarn install
    - cp .env.gitlab .env
    - cp config/database.ci.yml config/database.yml
    - cp db/structure.sql db/structure.sql.copia 
    - sed -e 's/provider = libc,//g;s/SET default_table_access_method.*/-- &/g' db/structure.sql.copia > db/structure.sql 
    - bundle exec bin/rails db:setup
    - bundle exec bin/rails sip:indices

test:
  stage: test
  needs: [build]
  script:
    - CONFIG_HOSTS=www.example.com bin/rails tes
